export const CATEGORIES_REPOSITORY = Symbol('CATEGORIES_REPOSITORY');
export const CATEGORIES_PRISMA_SERVICE = Symbol('CATEGORIES_PRISMA_SERVICE');
export const CATEGORIES_SERVICE = Symbol('CATEGORIES_SERVICE');
