export const PRODUCTS_REPOSITORY = Symbol('PRODUCTS_REPOSITORY');
export const PRODUCTS_PRISMA_SERVICE = Symbol('PRODUCTS_PRISMA_SERVICE');
export const PRODUCTS_SERVICE = Symbol('PRODUCTS_SERVICE');
